import type { TenantConfig } from "../types";
import { cedarHedgeFloorPlans } from "./floorplans";

/**
 * Smart Castle Homes · Cedar Hedge — first tenant.
 * Prices from smartcastle-homes pricing v5 (marketing; E&O.E.).
 * 3D paths are slots for human-delivered GLBs — set ready:true when files land.
 */
export const cedarHedgeTenant: TenantConfig = {
  slug: "cedar-hedge",
  builderName: "Smart Castle Homes",
  communityName: "Cedar Hedge",
  tagline: "36′ MultiGen detached — two homes in one.",
  location: "Milton, Ontario",
  productSummary:
    "Four elevations · unfinished basement or basement apartment plans · Multigenerational living.",
  theme: {
    background: "#0e1518",
    foreground: "#f2efe8",
    muted: "#9aadaf",
    accent: "#4a737e",
    accentSoft: "#6a94a0",
    gold: "#c5a46a",
    surface: "#162024",
    gradientFrom: "#0e1518",
    gradientTo: "#1a2e34",
  },
  contact: {
    email: "smartcastlehomes@gmail.com",
    phone: ["647.204.6601", "647.271.2302"],
    office: "6733 Mississauga Road, Suite 700, Mississauga, ON L5N 6J5",
    website: "https://smartcastlehomes.com/",
  },
  disclaimer:
    "Prices and specifications are marketing information only and subject to change without notice. E&O.E. Renderings and 3D views are artist’s concept.",
  models: [
    {
      code: "36A",
      name: "The Athabasca",
      elevation: "Athabasca",
      sqft: "2,702",
      plan: "4 Bedroom unfinished basement",
      price: 1_429_000,
      pricingAfterRebate: 1_299_000,
      beds: "4",
      baths: "3.5",
      exteriorAssetId: "athabasca-exterior",
      interiorAssetId: "athabasca-interior",
    },
    {
      code: "36B",
      name: "The Athabasca",
      elevation: "Athabasca",
      sqft: "3,382",
      plan: "4 Bed + basement apartment",
      price: 1_504_000,
      pricingAfterRebate: 1_374_000,
      beds: "5",
      baths: "4.5",
      exteriorAssetId: "athabasca-exterior",
      interiorAssetId: "athabasca-interior",
    },
    {
      code: "36C",
      name: "The Carleton",
      elevation: "Carleton",
      sqft: "2,702",
      plan: "4 Bedroom unfinished basement",
      price: 1_439_000,
      pricingAfterRebate: 1_309_000,
      beds: "4",
      baths: "3.5",
      exteriorAssetId: "carleton-exterior",
      interiorAssetId: "carleton-interior",
    },
    {
      code: "36D",
      name: "The Carleton",
      elevation: "Carleton",
      sqft: "3,382",
      plan: "4 Bed + basement apartment",
      price: 1_504_000,
      pricingAfterRebate: 1_374_000,
      beds: "5",
      baths: "4.5",
      exteriorAssetId: "carleton-exterior",
      interiorAssetId: "carleton-interior",
    },
    {
      code: "36E",
      name: "The Dalhousie",
      elevation: "Dalhousie",
      sqft: "2,702",
      plan: "4 Bedroom unfinished basement",
      price: 1_449_000,
      pricingAfterRebate: 1_319_000,
      beds: "4",
      baths: "3.5",
      exteriorAssetId: "dalhousie-exterior",
      interiorAssetId: "dalhousie-interior",
    },
    {
      code: "36F",
      name: "The Dalhousie",
      elevation: "Dalhousie",
      sqft: "3,382",
      plan: "4 Bed + basement apartment",
      price: 1_524_000,
      pricingAfterRebate: 1_394_000,
      beds: "5",
      baths: "4.5",
      exteriorAssetId: "dalhousie-exterior",
      interiorAssetId: "dalhousie-interior",
    },
    {
      code: "36G",
      name: "The Brock",
      elevation: "Brock",
      sqft: "2,702",
      plan: "4 Bedroom unfinished basement",
      price: 1_459_000,
      pricingAfterRebate: 1_329_000,
      beds: "4",
      baths: "3.5",
      exteriorAssetId: "brock-exterior",
      interiorAssetId: "brock-interior",
    },
    {
      code: "36H",
      name: "The Brock",
      elevation: "Brock",
      sqft: "3,382",
      plan: "4 Bed + basement apartment",
      price: 1_534_000,
      pricingAfterRebate: 1_404_000,
      beds: "5",
      baths: "4.5",
      exteriorAssetId: "brock-exterior",
      interiorAssetId: "brock-interior",
    },
  ],
  lots: [],
  assets: [
    {
      id: "athabasca-exterior",
      kind: "exterior",
      src: "/tenants/cedar-hedge/assets/exteriors/athabasca.glb",
      label: "Athabasca exterior elevation",
      modelCode: "36A",
      ready: false,
      format: "glb",
      notes: "Human 3D: exterior elevation GLB",
    },
    {
      id: "athabasca-interior",
      kind: "interior",
      src: "/tenants/cedar-hedge/assets/interiors/athabasca.glb",
      label: "Athabasca interior",
      modelCode: "36A",
      ready: false,
      format: "glb",
      notes: "Human 3D: interior layout GLB",
    },
    {
      id: "carleton-exterior",
      kind: "exterior",
      src: "/tenants/cedar-hedge/assets/exteriors/carleton.glb",
      label: "Carleton exterior elevation",
      modelCode: "36C",
      ready: false,
      format: "glb",
    },
    {
      id: "carleton-interior",
      kind: "interior",
      src: "/tenants/cedar-hedge/assets/interiors/carleton.glb",
      label: "Carleton interior",
      modelCode: "36C",
      ready: false,
      format: "glb",
    },
    {
      id: "dalhousie-exterior",
      kind: "exterior",
      src: "/tenants/cedar-hedge/assets/exteriors/dalhousie.glb",
      label: "Dalhousie exterior elevation",
      modelCode: "36E",
      ready: false,
      format: "glb",
    },
    {
      id: "dalhousie-interior",
      kind: "interior",
      src: "/tenants/cedar-hedge/assets/interiors/dalhousie.glb",
      label: "Dalhousie interior",
      modelCode: "36E",
      ready: false,
      format: "glb",
    },
    {
      id: "brock-exterior",
      kind: "exterior",
      src: "/tenants/cedar-hedge/assets/exteriors/brock.glb",
      label: "Brock exterior elevation",
      modelCode: "36G",
      ready: false,
      format: "glb",
    },
    {
      id: "brock-interior",
      kind: "interior",
      src: "/tenants/cedar-hedge/assets/interiors/brock.glb",
      label: "Brock interior",
      modelCode: "36G",
      ready: false,
      format: "glb",
    },
    {
      id: "site-context",
      kind: "site",
      src: "/tenants/cedar-hedge/assets/site/cedar-hedge-site.glb",
      label: "Cedar Hedge site context",
      ready: false,
      format: "glb",
      notes: "Optional community / site massing",
    },
  ],
  floorPlans: cedarHedgeFloorPlans,
  documents: [
    {
      label: "Floor plans (website)",
      href: "https://smartcastlehomes.com/cedar-hedge/floorplans.html",
    },
  ],
};
