import type { FloorPlanLevel } from "../types";

const base = "/tenants/cedar-hedge/assets/floorplans";

/**
 * Jeffries plan sheets with approximate room hotspots (% of image).
 * sceneId values are reserved for future interior GLB / room scenes.
 */
export const cedarHedgeFloorPlans: FloorPlanLevel[] = [
  {
    id: "main-standard",
    label: "Main floor",
    imageSrc: `${base}/jeffries_main_standard.png`,
    description: "Standard main floor — open dining/living, kitchen, great room, office.",
    hotspots: [
      { id: "main-deck", label: "Deck", x: 8, y: 1, w: 72, h: 8, sceneId: "room-deck" },
      {
        id: "main-breakfast",
        label: "Breakfast",
        x: 6,
        y: 9,
        w: 38,
        h: 12,
        dims: "13'7\" × 8'8\"",
        sceneId: "room-breakfast",
      },
      {
        id: "main-great-room",
        label: "Great Room",
        x: 46,
        y: 9,
        w: 40,
        h: 18,
        dims: "14'0\" × 14'0\"",
        sceneId: "room-great-room",
      },
      {
        id: "main-kitchen",
        label: "Kitchen",
        x: 6,
        y: 22,
        w: 38,
        h: 15,
        dims: "13'7\" × 11'8\"",
        sceneId: "room-kitchen",
      },
      {
        id: "main-office",
        label: "Office",
        x: 52,
        y: 30,
        w: 30,
        h: 13,
        dims: "10'1\" × 9'0\"",
        sceneId: "room-office",
      },
      {
        id: "main-dining",
        label: "Dining Room",
        x: 6,
        y: 40,
        w: 38,
        h: 13,
        dims: "13'7\" × 10'0\"",
        sceneId: "room-dining",
      },
      {
        id: "main-living",
        label: "Living Room",
        x: 6,
        y: 54,
        w: 46,
        h: 16,
        dims: "18'11\" × 11'0\"",
        sceneId: "room-living",
      },
      {
        id: "main-stairs",
        label: "Stairs",
        x: 48,
        y: 44,
        w: 18,
        h: 14,
        sceneId: "room-stairs-main",
      },
      {
        id: "main-pwd",
        label: "Powder Room",
        x: 68,
        y: 48,
        w: 14,
        h: 10,
        sceneId: "room-powder",
      },
      {
        id: "main-foyer",
        label: "Sunken Foyer",
        x: 54,
        y: 62,
        w: 30,
        h: 12,
        sceneId: "room-foyer",
      },
      {
        id: "main-porch",
        label: "Porch",
        x: 50,
        y: 78,
        w: 28,
        h: 12,
        sceneId: "room-porch",
      },
    ],
  },
  {
    id: "main-great-room",
    label: "Main · optional great room",
    imageSrc: `${base}/jeffries_main_great_room.png`,
    description: "Optional enlarged great room layout.",
    hotspots: [
      { id: "mgr-deck", label: "Deck", x: 8, y: 1, w: 72, h: 8, sceneId: "room-deck" },
      {
        id: "mgr-breakfast",
        label: "Breakfast",
        x: 6,
        y: 9,
        w: 36,
        h: 12,
        dims: "13'7\" × 8'8\"",
        sceneId: "room-breakfast",
      },
      {
        id: "mgr-great-room",
        label: "Great Room",
        x: 44,
        y: 9,
        w: 42,
        h: 28,
        dims: "14'0\" × 23'10\"",
        sceneId: "room-great-room",
      },
      {
        id: "mgr-kitchen",
        label: "Kitchen",
        x: 6,
        y: 22,
        w: 36,
        h: 15,
        dims: "13'7\" × 11'8\"",
        sceneId: "room-kitchen",
      },
      {
        id: "mgr-dining",
        label: "Dining Room",
        x: 6,
        y: 40,
        w: 36,
        h: 13,
        dims: "13'7\" × 10'0\"",
        sceneId: "room-dining",
      },
      {
        id: "mgr-living",
        label: "Living Room",
        x: 6,
        y: 54,
        w: 44,
        h: 16,
        dims: "18'11\" × 11'0\"",
        sceneId: "room-living",
      },
      {
        id: "mgr-foyer",
        label: "Sunken Foyer",
        x: 54,
        y: 62,
        w: 30,
        h: 12,
        sceneId: "room-foyer",
      },
    ],
  },
  {
    id: "second",
    label: "Second floor",
    imageSrc: `${base}/jeffries_second.png`,
    description: "Four bedrooms, ensuites, laundry.",
    hotspots: [
      {
        id: "sec-ensuite-master",
        label: "Master Ensuite",
        x: 4,
        y: 4,
        w: 36,
        h: 28,
        sceneId: "room-master-ensuite",
      },
      {
        id: "sec-master",
        label: "Master Bedroom",
        x: 48,
        y: 4,
        w: 44,
        h: 28,
        dims: "14'1\" × 17'8\"",
        sceneId: "room-master",
      },
      {
        id: "sec-wic",
        label: "Walk-in Closet",
        x: 36,
        y: 12,
        w: 14,
        h: 16,
        sceneId: "room-master-wic",
      },
      {
        id: "sec-bed-2",
        label: "Bedroom",
        x: 4,
        y: 36,
        w: 34,
        h: 16,
        dims: "11'4\" × 10'0\"",
        sceneId: "room-bed-2",
      },
      {
        id: "sec-ensuite-2",
        label: "Ensuite",
        x: 28,
        y: 52,
        w: 22,
        h: 14,
        sceneId: "room-ensuite-2",
      },
      {
        id: "sec-laundry",
        label: "Laundry",
        x: 58,
        y: 36,
        w: 28,
        h: 14,
        sceneId: "room-laundry",
      },
      {
        id: "sec-stairs",
        label: "Stairs / Skylight",
        x: 52,
        y: 48,
        w: 22,
        h: 14,
        sceneId: "room-stairs-second",
      },
      {
        id: "sec-bed-3",
        label: "Bedroom",
        x: 4,
        y: 70,
        w: 32,
        h: 18,
        dims: "10'0\" × 13'9\"",
        sceneId: "room-bed-3",
      },
      {
        id: "sec-ensuite-3",
        label: "Ensuite",
        x: 36,
        y: 72,
        w: 18,
        h: 14,
        sceneId: "room-ensuite-3",
      },
      {
        id: "sec-bed-4",
        label: "Bedroom",
        x: 56,
        y: 68,
        w: 32,
        h: 18,
        dims: "11'0\" × 10'1\"",
        sceneId: "room-bed-4",
      },
    ],
  },
  {
    id: "basement-standard",
    label: "Basement · unfinished",
    imageSrc: `${base}/jeffries_basement_standard.png`,
    description: "Standard unfinished basement with garage.",
    hotspots: [
      {
        id: "bs-garage",
        label: "Garage",
        x: 8,
        y: 48,
        w: 48,
        h: 36,
        dims: "18'5\" × 21'0\"",
        sceneId: "room-garage",
      },
      {
        id: "bs-stairs",
        label: "Stairs",
        x: 58,
        y: 40,
        w: 22,
        h: 20,
        sceneId: "room-stairs-basement",
      },
      {
        id: "bs-mech",
        label: "Mechanical",
        x: 58,
        y: 62,
        w: 28,
        h: 18,
        notes: "Furnace / HWT / sump — locations TBD",
        sceneId: "room-mechanical",
      },
    ],
  },
  {
    id: "basement-suite",
    label: "Basement · optional suite",
    imageSrc: `${base}/jeffries_basement_suite.png`,
    description: "Optional second suite — Multigen living.",
    hotspots: [
      {
        id: "suite-bed",
        label: "Bedroom",
        x: 6,
        y: 4,
        w: 36,
        h: 18,
        dims: "9'8\" × 10'2\"",
        sceneId: "room-suite-bed",
      },
      {
        id: "suite-living",
        label: "Living Room",
        x: 46,
        y: 4,
        w: 42,
        h: 18,
        dims: "12'9\" × 10'6\"",
        sceneId: "room-suite-living",
      },
      {
        id: "suite-den",
        label: "Den",
        x: 6,
        y: 24,
        w: 34,
        h: 16,
        dims: "10'0\" × 10'0\"",
        sceneId: "room-suite-den",
      },
      {
        id: "suite-bath",
        label: "Bath",
        x: 42,
        y: 24,
        w: 16,
        h: 16,
        sceneId: "room-suite-bath",
      },
      {
        id: "suite-kitchen",
        label: "Kitchen",
        x: 60,
        y: 22,
        w: 28,
        h: 22,
        dims: "8'0\" × 13'0\"",
        sceneId: "room-suite-kitchen",
      },
      {
        id: "suite-garage",
        label: "Garage",
        x: 8,
        y: 48,
        w: 48,
        h: 36,
        dims: "18'5\" × 21'0\"",
        sceneId: "room-garage",
      },
      {
        id: "suite-stairs",
        label: "Stairs",
        x: 58,
        y: 48,
        w: 22,
        h: 18,
        sceneId: "room-stairs-basement",
      },
    ],
  },
];
